apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: "license-scan-start-pipeline"
  annotations:
    description: |-
      Start the license scan pipeline passing in your git repo
    iconClass: icon-jenkins
objects:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      openshift.io/scc: restricted
    creationTimestamp: null
    labels:
      run: rhel-toolboxx
    name: rhel-toolboxx-${UNIQUE_VALUE}
  spec:
    containers:
    - command:
      - '/bin/bash'
      - '-c'
      - >
         oc get pods

         oc start-build license-scan-demo-pipeline --env=APPLICATION_SOURCE_REPO=${SOURCE_GIT_REPO}
      image: docker-registry.default.svc:5000/openshift/jenkins-slave-base-rhel7
      imagePullPolicy: IfNotPresent
      name: rhel-toolboxx
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: jenkins-token-sv2ln
        readOnly: true
    dnsPolicy: ClusterFirst
    imagePullSecrets:
    - name: default-dockercfg-2j92m
    restartPolicy: Never
    serviceAccount: jenkins
    serviceAccountName: jenkins
    terminationGracePeriodSeconds: 30
    volumes:
    - name: jenkins-token-sv2ln
      secret:
        defaultMode: 420
        secretName: jenkins-token-sv2ln
parameters:
- name: SOURCE_GIT_REPO
  displayName: Repo containing code to scan
  description: Name of repo to license scan
  value: https://github.com/malacourse/nodejs.git
  required: true
- name: UNIQUE_VALUE
  generate: expression
  from: "[a-z0-9]{5}"
  required: true

