apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: "license-plugin-scan-request"
  annotations:
    description: |-
      Start the license scan of a open source plugin project passing in your git repo
    iconClass: icon-jenkins
    tags: instant-app, jenkins
objects:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      openshift.io/scc: restricted
    creationTimestamp: null
    labels:
      run: plugin-license-scan
    name: plugin-license-scan-${UNIQUE_VALUE}
  spec:
    containers:
    - command:
      - '/bin/bash'
      - '-c'
      - >
         oc start-build plugin-license-scan-demo-pipeline -e CONTEXT_DIR=${CONTEXT_DIR} -e APPLICATION_SOURCE_REPO="${SOURCE_GIT_REPO}" -e ARTIFACT_NAME="${ARTIFACT_NAME}" -e APPROVAL_NOTES="${APPROVAL_NOTES}"
      image: docker-registry.default.svc:5000/openshift/jenkins-slave-base-rhel7
      imagePullPolicy: IfNotPresent
      name: plugin-scan
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: jenkins-token
        readOnly: true
    dnsPolicy: ClusterFirst
    #    imagePullSecrets:
    #- name: default-dockercfg-2j92m
    restartPolicy: Never
    serviceAccount: jenkins
    serviceAccountName: jenkins
    terminationGracePeriodSeconds: 30
    volumes:
    - name: jenkins-token
      secret:
        defaultMode: 420
        secretName: jenkins-token-dk72n 
parameters:
- name: SOURCE_GIT_REPO
  displayName: Repo containing code to scan
  description: Name of repo to license scan
  value: https://github.com/malacourse/scan-demo-java.git
  required: true
- name: ARTIFACT_NAME
  displayName: Name of package needing approval
  description: Name of package needing approval
  value: io.prometheus
  required: true
- name: APPROVAL_NOTES
  displayName: Notes for approver
  description: Notes for approver
  value: Please approve
  required: true
- name: CONTEXT_DIR
  displayName: Context Directory
  description: Context Dir
  value: "./"
  required: true
- name: UNIQUE_VALUE
  generate: expression
  from: "[a-z0-9]{5}"
  required: true

