apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: "license-docker-scan-request"
  annotations:
    description: |-
      Start the license scan of a openshift image
    iconClass: icon-jenkins
    tags: instant-app, jenkins
objects:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      openshift.io/scc: restricted
    creationTimestamp: null
    labels:
      run: docker-license-scan
    name: docker-license-scan-${UNIQUE_VALUE}
  spec:
    containers:
    - command:
      - '/bin/bash'
      - '-c'
      - >
         oc start-build docker-license-scan-demo-pipeline -e DOCKER_IMAGE="${DOCKER_IMAGE}" -e ARTIFACT_NAME="${ARTIFACT_NAME}" -e APPROVAL_NOTES="${APPROVAL_NOTES}"
      image: docker-registry.default.svc:5000/openshift/jenkins-slave-base-rhel7
      imagePullPolicy: IfNotPresent
      name: plugin-scan
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: jenkins-token
        readOnly: true
    dnsPolicy: ClusterFirst
    #    imagePullSecrets:
    #- name: default-dockercfg-2j92m
    restartPolicy: Never
    serviceAccount: jenkins
    serviceAccountName: jenkins
    terminationGracePeriodSeconds: 30
    volumes:
    - name: jenkins-token
      secret:
        defaultMode: 420
        secretName: jenkins-token-dk72n 
parameters:
- name: DOCKER_IMAGE
  displayName: Openshift Image to scan
  description: Image to scan
  value: docker-registry.default.svc:5000/cicd/nexus3
  required: true
- name: ARTIFACT_NAME
  displayName: Name of package needing approval
  description: Name of package needing approval
  value: nexus3
  required: true
- name: APPROVAL_NOTES
  displayName: Notes for approver
  description: Notes for approver
  value: Please approve
  required: true
- name: UNIQUE_VALUE
  generate: expression
  from: "[a-z0-9]{5}"
  required: true

